matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .github/spellcheck-wordlist.txt # <-- put path to custom dictionary file here
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - 'link_check/*.md'
  - 'link_check/*.cpp'
  
  default_encoding: utf-8
