build:
    # - build-arduino-wire-XMC4700
    - build-magnetic-w2b6


check:
    - check-clang-tidy
#     - check-cppcheck


example:
    - example-magnetic-w2b6-xmc100_xmc2go


monitor:
    - monitor-magnetic-w2b6-xmc100_xmc2go
