name: Build workflow with strategy

on:
  push:
    branches: [ workflow_test ]


defaults:
  run:
    shell: bash


jobs:

  setup:

    runs-on: ubuntu-24.04


    env:
      GHCR_REGISTRY: ghcr.io
      # issue : organization "Infineon" with capital "I" not allowed.
      IMAGE_NAME: infineon/makers-docker


    container:
      image: ghcr.io/infineon/makers-docker:latest

      credentials:
        username: infineon
        password: ${{ secrets.github_token }}

      volumes:
        - .:/myLocalWorkingDir:rw

      options: --cpus 1

    steps:

      - name: Checkout actions
        uses: actions/checkout@v4


      - name: Set strategy matrix
        id: set-matrix
        run: |
          eval $(python3 bin/build.py --getBuildJobs)


    outputs:
      build_jobs: ${{ steps.set-matrix.outputs.build_jobs }}


  flowStep:

    runs-on: ubuntu-24.04

    needs: setup

    container:
      image: ghcr.io/infineon/makers-docker:latest

      credentials:
        username: infineon
        password: ${{ secrets.github_token }}

      volumes:
        - .:/myLocalWorkingDir:rw

      options: --cpus 1


    strategy:

      matrix:
        build_jobs: ${{ fromJson(needs.setup.outputs.build_jobs) }}

    steps:

    - name: Checkout actions
      uses: actions/checkout@v4


    - name: Demo to show use of script to use matrix values
      id: run_build
      if: success() || failure()
      run: |
        echo "Workflow has these parameters :"
        echo "matrix.build_jobs   : " ${{ matrix.build_jobs }}
        echo ""

        bin/build.sh --runBuildJob ${{ matrix.build_jobs }}
